[workspace]
resolver = "2"
members = [
    "rlune", 
    "rlune-cli",
    "rlune-macros",
    "rlune-core",
    #    "contrib/rlune-contrib-auth",
    #    "contrib/rlune-contrib-tracing",
    # "example/blog",
    "example/blog",
    "swaggapi",  
]

[workspace.dependencies]
axum = { version = "~0.8", default-features = false }
rorm = { version = "*", git = "https://github.com/rorm-orm/rorm", tag = "v0.7.0-prrorm = { version = "*", git = "https://github.com/rorm-orm/rorm", branch = "dev", default-features = false, features = ["postgres-only"] }e-1", default-features = false, features = ["postgres-only"] }