[workspace]
resolver = "2"
members = [
    "rlune", 
    "rlune-cli",
    "rlune-macros",
    "rlune-core",
    "contrib/rlune-contrib-auth",
    "contrib/rlune-contrib-tracing",
    "example/blog",
    "swaggapi",  
]
